### ISSUE TITLE
Bangladesh's Data is incomplete

### ISSUE THREAD

**Issue by shubhansu-kr** [gdsclpu/OpenWorldAPI#102]
Bangladesh's data is missing in database. I would like to contribute to the database. 

Please Assign me this issue. 
Thanks in Advance.

**Comment by NikhilMahana** [comment]
Hey @shubhansu-kr,
You may start working on the issue now.
Happy Hacktoberfest.

**Comment by shubhansu-kr** [comment]
Hey @NikhilMahana,
Thanks for assigning me this Issue. 
I have created the PR #103 for the same. Please review and update me. 

Thanks
