### ISSUE TITLE
Aruba's data is incomplete 

### ISSUE THREAD

**Issue by shubhansu-kr** [gdsclpu/OpenWorldAPI#105]
I would like to add Aruba's geographical info to the database.
Please assign me this issue. 

Thanks in advance.

**Comment by Boanerges1996** [comment]
@shubhansu-kr you can work on this issue now

**Comment by shubhansu-kr** [comment]
Hey @Boanerges1996, 
Thanks for assigning me this issue. I have created a PR for the same. 
Please review the Pull #108. 

ThankYou
