### ISSUE TITLE
Algeria's data is incomplete

### ISSUE THREAD

**Issue by shubhansu-kr** [gdsclpu/OpenWorldAPI#113]
We are missing intel on Algeria. 
I would like to add the info to the database. 

Please assign me this issue. 
ThankYou.

**Comment by RamanSharma100** [comment]
@shubhansu-kr assigned you

**Comment by shubhansu-kr** [comment]
@RamanSharma100  Bhaiya, 
Thanks for assigning me this issue. I have created a PR for the same. 
Please Review the PR #115 (This one took a lot of effort :) )

ThankYou.
