### ISSUE TITLE
Invalid trailing commas in India.json

### ISSUE THREAD

**Issue by shubhansu-kr** [gdsclpu/OpenWorldAPI#65]
**Describe the bug**
Trailing commas in [india.json](./data/countries/india.json) file, which is causing server crash on local host. 

**To Reproduce**
1. Go to [./data/countries/india.json](./data/countries/india.json)
3. Scroll down to 'line 1042 and 1069'

**Comment by shubhansu-kr** [comment]
The local server crashed with the following error 

> SyntaxError: E:\Forks\OpenWorldAPI\data\countries\india.json: Unexpected token ] in JSON at position 22809
<img width="903" alt="image" src="https://user-images.githubusercontent.com/91339919/195996825-34b9829f-6012-4dea-b0fe-5cd071d617bf.png">

Upon checking, turned out it was simple trailing comma error.

**Comment by Vyvy-vi** [comment]
We should probably set up a linter github action.
