### ISSUE TITLE
Invalid Parameter Crashes APP 

### ISSUE THREAD

**Issue by shubhansu-kr** [gdsclpu/OpenWorldAPI#67]
**Description**
The app crashed upon serving an invalid GET request. 
While testing the district endpoints 'GET -> <url>/districts/get/all/districts/:country' using postman, an invalid request caused the server to crash.  

**To Reproduce**
Make a GET request for district list using postman as shown in screen shots below.

**Screenshots**
![image](https://user-images.githubusercontent.com/91339919/196002314-b8b7d399-68a7-490e-842d-4d0dab5282f3.png)
![image](https://user-images.githubusercontent.com/91339919/196002315-956a7f81-e3c8-4f0f-8dbe-c535d6b31ac7.png)
![image](https://user-images.githubusercontent.com/91339919/196002319-60d29910-90cd-4b1f-a05a-c13465a6c426.png)
![image](https://user-images.githubusercontent.com/91339919/196002325-7c20e6f2-26a0-4f1e-8865-09af8e171ea3.png)

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser: Google Chrome
 - Version 106.0.5249.119 (Official Build) (64-bit)

**Additional context**
May not be a bug since, the app works fine on [openworldapi.tech](https://openworldapi.tech/).

**Comment by Boanerges1996** [comment]
@shubhansu-kr this error should be fixed now. Try out and then close the issue if it works

**Comment by shubhansu-kr** [comment]
> @shubhansu-kr this error should be fixed now. Try out and then close the issue if it works

Thank you for fixing the issue.
I believe the issue has been verified since the issue is already closed by the @smanitech.
